export { Home } from './Home'
export { Movies } from './Movies'
export { Movie } from './[Movie]'
export { About } from './About'
export { TvShows } from './TvShows'
export { Profile } from './Profile'
export { Peoples } from './Peoples'
export { Search } from './Search'